apiVersion: downscaler.go/v1alpha1
kind: Downscaler
metadata:
  name: downscaler
  namespace: downscaler
spec:
  config:
    cronLoggerInterval: 30
  schedule:
    timeZone: "America/Sao_Paulo"
    recurrence: "@daily"
  downscalerOptions:
    resourceScaling:
      - deployments
      - statefulset
    timeRules:
      rules:
        - name: "Rule to downscale deployments from requirement A"
          namespaces:
          - "app"
          - "app2"
          upscaleTime: "17:14"
          downscaleTime: "17:13"
          overrideScaling: ["deployments", "statefulset"]

        - name: "Rule to downscale deployments from requirement B"
          namespaces:
          - "app3"
          - "app4"
          upscaleTime: "17:14"
          downscaleTime: "17:13"

        - name: "Rule to downscale statefulset from requirement C"
          namespaces:
          - "app10"
          upscaleTime: "17:14"
          downscaleTime: "17:13"