apiVersion: downscaler.go/v1alpha1
kind: Downscaler
metadata:
  name: downscaler
  namespace: downscaler
spec:
  config:
    cronLoggerInterval: 10 
  schedule:
    timeZone: "America/Sao_Paulo"
    recurrence: "MON-SAT"
  namespacesRules:
    exclude:
      namespaces:
        - "namespace1"
        - "namespace2"
        - "namespace3"
    include:
      withRulesByNamespaces:
        rules:
          - namespaces:
              - "app"
            upscaleTime: "15:40"
            downscaleTime: "15:39"
