apiVersion: downscaler.go/v1alpha1
kind: Downscaler
metadata:
  name: downscaler
  namespace: downscaler
spec:
  config:
    cronLoggerInterval: 20 
  schedule:
    timeZone: "America/Sao_Paulo"
    recurrence: "MON-SAT"
  namespacesRules:
    exclude:
      namespaces:
        - "app2"
        - "app3"
        - "app4"
    include:
      withRulesByNamespaces:
        rules:
          - namespaces:
              - "app"
            upscaleTime: "17:10"
            downscaleTime: "17:08"
          - namespaces:
              - "app5"
            upscaleTime: "17:09"
            downscaleTime: "17:08"
          - namespaces:
              - "any"
            upscaleTime: "17:09"
            downscaleTime: "17:08"

