apiVersion: downscaler.go/v1alpha1
kind: Downscaler
metadata:
  name: downscaler
  namespace: downscaler
spec:
  config:
    cronLoggerInterval: 30
    persistence: true
  schedule:
    timeZone: "America/Sao_Paulo"
    recurrence: "@daily"
  downscalerOptions:
    resourceScaling:
      - deployments
      - hpa
      - statefulset
    timeRules:
      rules:
        - name: "Rule to downscale deployments from requirement A"
          namespaces:
          - "app"
          - "app2"
          upscaleTime: "17:11"
          downscaleTime: "17:09"
          overrideScaling: ["deployments", "statefulset", "hpa"]

        - name: "Rule to downscale deployments from requirement B"
          namespaces:
          - "app3"
          - "app4"
          upscaleTime: "17:11"
          downscaleTime: "17:09"

        - name: "Rule to downscale statefulset from requirement C"
          namespaces:
          - "app10"
          upscaleTime: "17:11"
          downscaleTime: "17:09"