apiVersion: downscaler.go/v1alpha1
kind: Downscaler
metadata:
  name: downscaler
  namespace: downscaler
spec:
  config:
    cronLoggerInterval: 10
  schedule:
    timeZone: "America/Sao_Paulo"
    recurrence: "@daily"
  downscalerOptions:
    timeRules:
      rules:
        - namespaces:
          - "app"
          - "app2"
          upscaleTime: "15:23"
          downscaleTime: "15:25"