# permissions for end users to edit downscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operatordownscaler
    app.kubernetes.io/managed-by: kustomize
  name: downscaler-editor-role
rules:
- apiGroups:
  - downscaler.go
  resources:
  - downscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - downscaler.go
  resources:
  - downscalers/status
  verbs:
  - get
