---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - downscaler.go
  resources:
  - downscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - downscaler.go
  resources:
  - downscalers/finalizers
  verbs:
  - update
- apiGroups:
  - downscaler.go
  resources:
  - downscalers/status
  verbs:
  - get
  - patch
  - update
